const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const root = path.join(__dirname, '..');

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), 'utf8');
}

test('modern front-end is now the default experience and classic files are preserved', () => {
  const html = read('public/modern.html');
  const defaultHtml = read('public/index.html');
  const classicHtml = read('public/classic.html');
  const css = read('public/modern.css');
  const js = read('public/modern.js');

  assert.match(html, /id="modern-intro" class="modern-intro"/);
  assert.match(defaultHtml, /id="modern-intro" class="modern-intro"/);
  assert.match(classicHtml, /id="home-section"[\s\S]*class="home-section active"/);
  assert.match(html, /class="modern-intro-title"[\s\S]*把难开口的心事，放进这一页/);
  assert.match(html, /id="modern-enter-btn"[\s\S]*开始问一件事/);
  assert.match(html, /id="modern-composer-section" class="modern-composer-section" hidden/);
  assert.match(html, /id="modern-question"/);
  assert.match(html, /id="modern-submit"[\s\S]*立即算一算/);
  assert.match(html, /class="modern-chip" data-question=/);
  assert.match(html, /id="modern-question-guide"/);
  assert.match(html, /id="modern-question-coach"/);
  assert.match(html, /帮我把问题问清楚/);
  assert.match(html, /data-coach-field="worry"/);
  assert.match(html, /data-coach-field="direction"/);
  assert.match(html, /id="modern-recent-questions" class="modern-recent-questions"/);
  assert.match(defaultHtml, /id="modern-recent-questions" class="modern-recent-questions"/);
  assert.equal(defaultHtml, html);
  assert.match(html, /id="modern-question-helper" class="modern-tips"/);
  assert.match(html, /不知道怎么写？打开提问助手/);
  assert.match(html, /class="modern-helper-template" data-template=/);
  assert.match(html, /id="modern-result-shell" class="modern-result-shell" hidden/);
  assert.match(html, /id="modern-judgment-content"/);
  assert.match(html, /class="modern-judgment-text is-pending"/);
  assert.match(html, /id="modern-hexagram-title"/);
  assert.match(html, /id="modern-current-explanation"/);
  assert.match(html, /id="modern-changing-explanation"/);
  assert.match(html, /id="modern-future-explanation"/);
  assert.match(html, /class="modern-changed-summary-hint"[\s\S]*点开看看这件事接下来可能怎么走/);
  assert.match(html, /id="modern-changed-search-query"/);
  assert.match(html, /id="modern-changed-search-copy"[\s\S]*复制搜索词/);
  assert.match(html, /id="modern-changed-search-link"[\s\S]*去搜一下/);
  assert.match(html, /id="modern-interpretation-emotion"/);
  assert.match(html, /id="modern-interpretation-main"/);
  assert.match(html, /id="modern-rephrase"[\s\S]*换个问法再问/);
  assert.match(html, /id="modern-reset"[\s\S]*问一件新的事/);
  assert.match(html, /id="modern-followup-panel"/);
  assert.match(html, /data-followup="advance"/);
  assert.match(html, /data-followup="wait"/);
  assert.match(html, /data-followup="notice"/);
  assert.match(html, /id="modern-share"[\s\S]*保存心安卡片/);
  assert.match(html, /class="modern-intro-aside"/);
  assert.match(html, /class="modern-result-masthead"/);
  assert.match(html, /class="modern-hexagram-caption"/);
  assert.match(html, /class="modern-footer-link"[\s\S]*存档页/);

  assert.match(css, /\.modern-topbar/);
  assert.match(css, /\.modern-intro/);
  assert.match(css, /\.modern-body\.entered \.modern-intro/);
  assert.match(css, /\.modern-composer-shell/);
  assert.match(css, /\.modern-judgment-card/);
  assert.match(css, /\.modern-judgment-text\.is-pending/);
  assert.match(css, /@keyframes modernJudgmentPulse/);
  assert.match(css, /\.modern-tips/);
  assert.match(css, /\.modern-question-guide/);
  assert.match(css, /\.modern-question-coach/);
  assert.match(css, /\.modern-coach-pill/);
  assert.match(css, /\.modern-recent-questions/);
  assert.match(css, /\.modern-recent-empty/);
  assert.match(css, /\.modern-recent-item/);
  assert.match(css, /\.modern-helper-templates/);
  assert.match(css, /\.modern-helper-template/);
  assert.match(css, /\.modern-change-story/);
  assert.match(css, /\.modern-changed-note/);
  assert.match(css, /\.modern-changed-summary-icon/);
  assert.match(css, /\.modern-changed-search-query/);
  assert.match(css, /\.modern-inline-btn/);
  assert.match(css, /\.modern-hexagram-stage/);
  assert.match(css, /\.modern-hexagram-board-wrap[\s\S]*justify-content:\s*center/);
  assert.match(css, /\.modern-line-slot[\s\S]*width:\s*min\(220px,\s*50%\)/);
  assert.match(css, /\.modern-reading-flow/);
  assert.match(css, /\.modern-intro-frame/);
  assert.match(css, /\.modern-aside-card/);
  assert.match(css, /\.modern-reading-card-main::before/);
  assert.match(css, /\.modern-share-judgment/);
  assert.match(css, /\.modern-share-eyebrow/);
  assert.match(css, /\.modern-followup-panel/);
  assert.match(css, /\.modern-followup-btn/);
  assert.match(css, /\.share-mode \.modern-result-actions/);
  assert.match(css, /\.modern-line-changing/);
  assert.match(css, /--page-bg:\s*#f3ece2/);
  assert.match(css, /--accent-umber:\s*#6e4f43/);
  assert.match(css, /--font-display:\s*"ZCOOL XiaoWei"/);
  assert.match(css, /\.modern-intro-title[\s\S]*font-family:\s*var\(--font-display\)/);
  assert.match(css, /\.modern-share-quote[\s\S]*font-family:\s*var\(--font-display\)/);
  assert.match(css, /\.modern-share-quote[\s\S]*font-size:\s*clamp\(1\.82rem,\s*3\.4vw,\s*3rem\)/);
  assert.match(css, /\.modern-share-card\[aria-hidden="true"\]/);
  assert.match(css, /\.modern-reading-content-main[\s\S]*line-height:\s*2\.08/);

  assert.match(js, /function revealComposer\(/);
  assert.match(js, /function trackEvent\(/);
  assert.match(js, /navigator\.sendBeacon/);
  assert.match(js, /function updateQuestionGuide\(/);
  assert.match(js, /function updateQuestionCoach\(/);
  assert.match(js, /function applyCoachPrompt\(/);
  assert.match(js, /question_coach_click/);
  assert.match(js, /我担心的是/);
  assert.match(js, /我最想知道的是/);
  assert.match(js, /xinan_recent_questions/);
  assert.match(js, /const RECENT_QUESTION_LIMIT = 3/);
  assert.match(js, /function readRecentQuestions\(/);
  assert.match(js, /function renderRecentQuestions\(/);
  assert.match(js, /function saveRecentQuestion\(/);
  assert.match(js, /function useRecentQuestion\(/);
  assert.match(js, /localStorage\.setItem\(RECENT_QUESTION_KEY/);
  assert.match(js, /questionInput\.value = item\.question/);
  assert.match(js, /body\.classList\.add\('entered'\)/);
  assert.match(js, /function setJudgmentLoadingState\(/);
  assert.match(js, /function buildInstantJudgmentPreview\(/);
  assert.match(js, /fetch\('\/api\/divine'/);
  assert.match(js, /fetch\('\/api\/interpret'/);
  assert.match(js, /function renderInterpretationSections\(/);
  assert.match(js, /function deriveFallbackJudgment\(/);
  assert.match(js, /function cleanJudgmentCandidate\(/);
  assert.match(js, /function isUsableJudgmentCandidate\(/);
  assert.match(js, /function extractHealingLine\(/);
  assert.match(js, /candidate\.length < 6/);
  assert.match(js, /candidate\.length > 36/);
  assert.match(js, /function renderHexagram\(/);
  assert.match(js, /function updateChangedStory\(/);
  assert.match(js, /function buildHexagramSearchKeyword\(/);
  assert.match(js, /function setChangedSummary\(/);
  assert.match(js, /function formatChangingPositions\(/);
  assert.match(js, /function startDivination\(/);
  assert.match(js, /isSubmitting/);
  assert.match(js, /activeRequestId/);
  assert.match(js, /AbortController/);
  assert.match(js, /function abortActiveRequest\(/);
  assert.match(js, /function setResultActionsEnabled\(/);
  assert.match(js, /function startInterpretation\(/);
  assert.match(js, /resetInterpretationBlocks\(\{ preserveJudgment: true \}\)/);
  assert.match(js, /renderInterpretationSections\(currentText, \{ allowFallback: false \}\)/);
  assert.match(js, /renderInterpretationSections\(currentText, \{ allowFallback: true \}\)/);
  assert.match(js, /function saveShareImage\(/);
  assert.match(js, /function compactText\(/);
  assert.match(js, /function buildFollowupQuestion\(/);
  assert.match(js, /function followupFlow\(/);
  assert.match(js, /window\.html2canvas/);
  assert.match(js, /window\.html2canvas\(shareCard/);
  assert.match(js, /navigator\.clipboard\?\.writeText/);
  assert.match(js, /function rephraseFlow\(/);
  assert.match(js, /enter_click/);
  assert.match(js, /chip_click/);
  assert.match(js, /assistant_template_click/);
  assert.match(js, /submit_click/);
  assert.match(js, /divine_success/);
  assert.match(js, /interpret_complete/);
  assert.match(js, /recent_question_saved/);
  assert.match(js, /recent_question_click/);
  assert.match(js, /share_click/);
  assert.match(js, /share_generate_success/);
  assert.match(js, /share_generate_error/);
  assert.match(js, /question_draft_started/);
  assert.match(js, /page_view/);
  assert.match(js, /changed_shell_open/);
  assert.match(js, /copy_changed_search/);
  assert.match(js, /followup_question_click/);
  assert.match(js, /backgroundColor: '#f3ece2'/);
  assert.match(html, /fonts\.googleapis\.com\/css2\?family=Cormorant\+Garamond/);
  assert.match(html, /family=Noto\+Sans\+SC/);
  assert.match(html, /family=Noto\+Serif\+SC/);
  assert.match(html, /family=ZCOOL\+XiaoWei/);
});

test('analytics summary translates events into product decisions', () => {
  const analytics = read('scripts/analytics-summary.js');

  assert.match(analytics, /产品判断面板/);
  assert.match(analytics, /北极星指标/);
  assert.match(analytics, /当前最大掉点/);
  assert.match(analytics, /下一步建议/);
  assert.match(analytics, /function rateValue\(/);
  assert.match(analytics, /function findWeakestStep\(/);
  assert.match(analytics, /function buildProductInsights\(/);
  assert.match(analytics, /保存率/);
  assert.match(analytics, /追问率/);
});

test('server exposes privacy-safe analytics endpoint and ignores local analytics logs', () => {
  const server = read('server.js');
  const gitignore = read('.gitignore');

  assert.match(server, /app\.post\('\/api\/track'/);
  assert.match(server, /analytics_events\.log/);
  assert.match(server, /sanitizeAnalyticsPayload/);
  assert.match(server, /不记录用户提问原文/);
  assert.match(server, /sessionId/);
  assert.match(server, /viewportWidth/);
  assert.match(gitignore, /analytics_events\.log/);
});
