const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const root = path.join(__dirname, '..');

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), 'utf8');
}

function functionBlock(source, name) {
  const start = source.indexOf(`function ${name}(`);
  assert.notEqual(start, -1, `missing function ${name}`);
  const next = source.indexOf('\n    function ', start + 1);
  return next === -1 ? source.slice(start) : source.slice(start, next);
}

test('modern front-end is now the default experience and classic files are preserved', () => {
  const html = read('public/modern.html');
  const defaultHtml = read('public/index.html');
  const classicHtml = read('public/classic.html');
  const css = read('public/modern.css');
  const js = read('public/modern.js');

  assert.match(html, /id="modern-intro" class="modern-intro"/);
  assert.match(defaultHtml, /id="modern-intro" class="modern-intro"/);
  assert.match(classicHtml, /id="home-section"[\s\S]*class="home-section active"/);
  assert.match(html, /class="modern-intro-title"[\s\S]*把难开口的心事，放进这一页/);
  assert.match(html, /id="modern-enter-btn"[\s\S]*开始问一件事/);
  assert.match(html, /id="modern-composer-section" class="modern-composer-section" hidden/);
  assert.match(html, /id="modern-question"/);
  assert.match(html, /id="modern-submit"[\s\S]*立即算一算/);
  assert.match(html, /class="modern-chip" data-question=/);
  assert.match(html, /id="modern-question-guide"/);
  assert.match(html, /id="modern-question-coach"/);
  assert.match(html, /我帮你把问题问清楚/);
  assert.match(html, /id="modern-coach-heard-event"/);
  assert.match(html, /id="modern-coach-suggested-question"/);
  assert.match(html, /data-coach-field="useSuggestion"/);
  assert.match(html, /data-coach-field="rewrite"/);
  assert.match(html, /data-coach-field="specific"/);
  assert.match(html, /id="modern-recent-questions" class="modern-recent-questions"/);
  assert.match(defaultHtml, /id="modern-recent-questions" class="modern-recent-questions"/);
  assert.equal(defaultHtml, html);
  assert.match(html, /id="modern-question-helper" class="modern-tips"/);
  assert.match(html, /好问题通常包含什么？/);
  assert.match(html, /这不是考试，不用写得很完整/);
  assert.match(html, /class="modern-helper-template" data-template=/);
  assert.match(html, /id="modern-result-shell" class="modern-result-shell" hidden/);
  assert.match(html, /id="modern-judgment-content"/);
  assert.match(html, /id="modern-judgment-support"/);
  assert.match(html, /id="modern-judgment-progress"/);
  assert.match(html, /data-judgment-step="cast"/);
  assert.match(html, /data-judgment-step="translate"/);
  assert.match(html, /data-judgment-step="settle"/);
  assert.match(html, /class="modern-judgment-text is-pending"/);
  assert.match(html, /id="modern-hexagram-title"/);
  assert.match(html, /id="modern-current-explanation"/);
  assert.match(html, /id="modern-changing-explanation"/);
  assert.match(html, /id="modern-future-explanation"/);
  assert.match(html, /class="modern-changed-summary-title"[\s\S]*这卦有变化点，可以继续问这一层/);
  assert.match(html, /class="modern-changed-summary-cta"[\s\S]*点开追问动爻/);
  assert.match(html, /id="modern-changed-followup"/);
  assert.match(html, /id="modern-changed-followup-copy"[\s\S]*动爻就是这件事最容易变化的地方/);
  assert.match(html, /data-changed-followup="meaning"[\s\S]*动爻在提醒我看什么/);
  assert.match(html, /data-changed-followup="move"[\s\S]*顺着变还是先稳住/);
  assert.match(html, /data-changed-followup="attention"[\s\S]*这个变化点要注意什么/);
  assert.match(html, /id="modern-interpretation-emotion"/);
  assert.match(html, /id="modern-interpretation-main"/);
  assert.match(html, /id="modern-rephrase"[\s\S]*换个问法再问/);
  assert.match(html, /id="modern-reset"[\s\S]*问一件新的事/);
  assert.match(html, /id="modern-followup-panel"/);
  assert.match(html, /data-followup="advance"/);
  assert.match(html, /data-followup="wait"/);
  assert.match(html, /data-followup="notice"/);
  assert.match(html, /id="modern-share"[\s\S]*保存心安卡片/);
  assert.match(html, /id="modern-auth-modal"[\s\S]*继续问，需要先登录/);
  assert.match(html, /id="modern-wechat-login"[\s\S]*微信登录/);
  assert.match(html, /id="modern-phone-input"/);
  assert.match(html, /id="modern-send-code"[\s\S]*获取验证码/);
  assert.match(html, /id="modern-code-input"/);
  assert.match(html, /id="modern-verify-code"[\s\S]*手机号登录/);
  assert.match(html, /class="modern-intro-aside"/);
  assert.match(html, /class="modern-result-masthead"/);
  assert.match(html, /class="modern-hexagram-caption"/);
  assert.match(html, /class="modern-footer-link"[\s\S]*存档页/);

  assert.match(css, /\.modern-topbar/);
  assert.match(css, /scroll-margin-top:\s*132px/);
  assert.match(css, /@keyframes composerFadeIn\s*{\s*from\s*{\s*opacity:\s*0;\s*}\s*to\s*{\s*opacity:\s*1;\s*}/);
  assert.doesNotMatch(css, /\.modern-composer-shell[\s\S]*?backdrop-filter:\s*blur\(10px\)/);
  assert.match(css, /\.modern-intro/);
  assert.match(css, /\.modern-body\.entered \.modern-intro/);
  assert.match(css, /\.modern-composer-shell/);
  assert.match(css, /\.modern-judgment-card/);
  assert.match(css, /\.modern-judgment-support/);
  assert.match(css, /\.modern-judgment-progress/);
  assert.match(css, /\.modern-judgment-step/);
  assert.match(css, /\.modern-judgment-step\.is-active/);
  assert.match(css, /\.modern-judgment-step\.is-done/);
  assert.match(css, /\.modern-judgment-text\.is-pending/);
  assert.match(css, /@keyframes modernJudgmentPulse/);
  assert.match(css, /\.modern-tips/);
  assert.match(css, /\.modern-question-guide/);
  assert.match(css, /\.modern-question-coach/);
  assert.match(css, /\.modern-coach-heard/);
  assert.match(css, /\.modern-coach-suggestion/);
  assert.match(css, /\.modern-coach-pill/);
  assert.match(css, /\.modern-recent-questions/);
  assert.match(css, /\.modern-recent-empty/);
  assert.match(css, /\.modern-recent-item/);
  assert.match(css, /\.modern-helper-templates/);
  assert.match(css, /\.modern-helper-template/);
  assert.match(css, /\.modern-change-story/);
  assert.match(css, /\.modern-changed-note/);
  assert.match(css, /\.modern-changed-summary-icon/);
  assert.match(css, /\.modern-changed-summary-cta/);
  assert.match(css, /\.modern-changed-followup/);
  assert.match(css, /\.modern-changed-followup-btn/);
  assert.match(css, /\.modern-inline-btn/);
  assert.match(css, /\.modern-hexagram-stage/);
  assert.match(css, /\.modern-hexagram-board-wrap[\s\S]*justify-content:\s*center/);
  assert.match(css, /\.modern-line-slot[\s\S]*width:\s*min\(200px,\s*50%\)/);
  assert.match(css, /\.modern-reading-flow/);
  assert.match(css, /\.modern-intro-frame/);
  assert.match(css, /\.modern-aside-card/);
  assert.match(css, /\.modern-reading-card-main::before/);
  assert.match(css, /\.modern-share-judgment/);
  assert.match(css, /\.modern-share-eyebrow/);
  assert.match(css, /\.modern-followup-panel/);
  assert.match(css, /\.modern-followup-btn/);
  assert.match(css, /\.modern-auth-modal/);
  assert.match(css, /\.modern-auth-backdrop/);
  assert.match(css, /\.modern-auth-card/);
  assert.match(css, /\.modern-auth-methods/);
  assert.match(css, /\.share-mode \.modern-result-actions/);
  assert.match(css, /\.modern-line-changing/);
  assert.match(css, /--page-bg:\s*#f3ece2/);
  assert.match(css, /--accent-umber:\s*#6e4f43/);
  assert.match(css, /--font-display:\s*"ZCOOL XiaoWei"/);
  assert.match(css, /\.modern-intro-title[\s\S]*font-family:\s*var\(--font-display\)/);
  assert.match(css, /\.modern-share-quote[\s\S]*font-family:\s*var\(--font-display\)/);
  assert.match(css, /\.modern-share-quote[\s\S]*font-size:\s*clamp\(1\.95rem,\s*3\.2vw,\s*2\.85rem\)/);
  assert.match(css, /\.modern-share-card\[aria-hidden="true"\]/);
  assert.match(css, /\.modern-reading-content-main[\s\S]*line-height:\s*2\.15/);
  assert.match(css, /\.modern-reading-card strong/);
  assert.match(css, /\.modern-reading-content-main strong/);
  assert.match(css, /\.modern-reading-card \.zhouyi-term/);
  assert.match(css, /\.modern-primary-btn\.is-loading::after[\s\S]*content:\s*attr\(data-loading-label\)/);
  assert.match(css, /@keyframes loadingTextPulse/);
  assert.match(css, /\.modern-primary-btn\.is-success/);

  assert.match(js, /function revealComposer\(/);
  assert.match(js, /function trackEvent\(/);
  assert.match(js, /navigator\.sendBeacon/);
  assert.match(js, /function setSubmitState\(text, disabled, options = \{\}\)/);
  assert.match(js, /submitBtn\.classList\.toggle\('is-loading', isLoading\)/);
  assert.match(js, /submitBtn\.dataset\.loadingLabel = text/);
  assert.match(js, /function updateQuestionGuide\(/);
  assert.match(js, /SHORT_INTENT_PATTERN/);
  assert.match(js, /questionCoach\.hidden = !shouldShowCoach/);
  assert.match(js, /function updateQuestionCoach\(/);
  assert.match(js, /function buildCoachQuestion\(/);
  assert.match(js, /function summarizeCoachEvent\(/);
  assert.match(js, /function applyCoachPrompt\(/);
  assert.match(js, /question_coach_click/);
  assert.match(js, /useSuggestion/);
  assert.match(js, /rewrite/);
  assert.match(js, /specific/);
  assert.match(js, /function extractCoachIssue\(/);
  assert.match(js, /我现在真正卡住的点是什么/);
  assert.match(js, /我最需要先看清什么/);
  assert.match(js, /才不会越想越乱/);
  assert.match(js, /帮你收成一个更好问的问题/);
  assert.match(js, /xinan_recent_questions/);
  assert.match(js, /const RECENT_QUESTION_LIMIT = 3/);
  assert.match(js, /function readRecentQuestions\(/);
  assert.match(js, /function renderRecentQuestions\(/);
  assert.match(js, /function saveRecentQuestion\(/);
  assert.match(js, /function useRecentQuestion\(/);
  assert.match(js, /localStorage\.setItem\(RECENT_QUESTION_KEY/);
  assert.match(js, /questionInput\.value = item\.question/);
  assert.match(js, /body\.classList\.add\('entered'\)/);
  assert.match(js, /function setJudgmentLoadingState\(/);
  assert.match(js, /function setJudgmentProgressState\(/);
  assert.match(js, /function showJudgmentProgress\(/);
  assert.match(js, /function showFinalJudgment\(/);
  assert.doesNotMatch(js, /source: 'preview'/);
  assert.doesNotMatch(js, /function buildInstantJudgmentPreview\(/);
  assert.doesNotMatch(js, /function buildInstantJudgmentSupport\(/);
  assert.match(js, /fetch\('\/api\/divine'/);
  assert.match(js, /fetch\('\/api\/interpret'/);
  assert.match(js, /function renderInterpretationSections\(/);
  assert.match(js, /function renderInlineMarkdown\(/);
  assert.match(js, /renderInlineMarkdown\(text\)\.replace\(\/\\n\/g, '<br>'\)/);
  assert.match(js, /\(本卦\|动爻\|之卦\)/);
  assert.match(js, /function deriveFallbackJudgment\(/);
  assert.match(js, /function cleanJudgmentCandidate\(/);
  assert.match(js, /function firstCompleteSentence\(/);
  assert.match(js, /function isUsableJudgmentCandidate\(/);
  assert.match(js, /function extractHealingLine\(/);
  assert.match(js, /candidate\.length < 6/);
  assert.match(js, /candidate\.length > 52/);
  assert.match(js, /function renderHexagram\(/);
  assert.match(js, /function updateChangedStory\(/);
  assert.match(js, /function buildChangedFollowupQuestion\(/);
  assert.match(js, /function changedFollowupFlow\(/);
  assert.match(js, /function setChangedSummary\(/);
  assert.match(js, /动爻这个变化点在提醒我看什么/);
  assert.match(js, /面对动爻显示的变化点/);
  assert.match(js, /动爻这个位置最需要我注意什么/);
  assert.match(js, /function formatChangingPositions\(/);
  assert.match(js, /function startDivination\(/);
  assert.match(js, /window\.location\.protocol === 'file:'/);
  assert.match(js, /请访问 http:\/\/localhost:3000\/ 再起卦/);
  assert.match(js, /isSubmitting/);
  assert.match(js, /activeRequestId/);
  assert.match(js, /AbortController/);
  assert.match(js, /function abortActiveRequest\(/);
  assert.match(js, /function setResultActionsEnabled\(/);
  assert.match(js, /const GUEST_ID_KEY = 'xinan_guest_id'/);
  assert.match(js, /const GUEST_QUESTION_USED_KEY = 'xinan_guest_question_used'/);
  assert.match(js, /const AUTH_GATE_ENABLED = false/);
  assert.match(js, /function getGuestId\(/);
  assert.match(js, /function loadAuthState\(/);
  assert.match(js, /function showAuthModal\(/);
  assert.match(js, /function requireLoginForContinuation\(/);
  assert.match(js, /if \(!AUTH_GATE_ENABLED\) return true/);
  assert.match(js, /function requestPhoneCode\(/);
  assert.match(js, /function verifyPhoneCode\(/);
  assert.match(js, /function startWechatLogin\(/);
  assert.match(js, /'X-Guest-Id': getGuestId\(\)/);
  assert.match(js, /LOGIN_REQUIRED/);
  assert.match(js, /function startInterpretation\(/);
  assert.match(js, /function renderInterpretationFailure\(/);
  assert.match(js, /卦已经起好，但大白话解读暂时没连上/);
  assert.match(js, /statusPill\.textContent === '正在解读'/);
  assert.match(js, /resetInterpretationBlocks\(\{ preserveJudgment: true \}\)/);
  assert.match(js, /renderInterpretationSections\(currentText, \{ allowFallback: false \}\)/);
  assert.match(js, /renderInterpretationSections\(currentText, \{ allowFallback: true \}\)/);
  assert.match(js, /function saveShareImage\(/);
  assert.match(js, /function compactText\(/);
  assert.match(js, /function stripChangedTitleFromQuestion\(/);
  assert.match(js, /function completeShareContext\(/);
  assert.match(js, /function extractConflictTag\(/);
  assert.match(js, /function completeShareQuote\(/);
  assert.match(js, /function isWarmShareQuoteCandidate\(/);
  assert.match(js, /慢一点没关系，先把自己放稳，答案会慢慢清楚。/);
  assert.match(js, /function buildFollowupQuestion\(/);
  assert.match(js, /function followupFlow\(/);
  assert.match(js, /function showFollowupComposer\(/);
  assert.doesNotMatch(functionBlock(js, 'followupFlow'), /resultShell\.hidden = true|composerSection\.scrollIntoView/);
  assert.doesNotMatch(functionBlock(js, 'changedFollowupFlow'), /resultShell\.hidden = true|composerSection\.scrollIntoView/);
  assert.match(js, /window\.html2canvas/);
  assert.match(js, /window\.html2canvas\(shareCard/);
  assert.match(js, /let didSave = false/);
  assert.match(js, /if \(didSave\) \{/);
  assert.match(js, /function rephraseFlow\(/);
  assert.match(js, /enter_click/);
  assert.match(js, /chip_click/);
  assert.match(js, /assistant_template_click/);
  assert.match(js, /submit_click/);
  assert.match(js, /divine_success/);
  assert.match(js, /interpret_complete/);
  assert.match(js, /recent_question_saved/);
  assert.match(js, /recent_question_click/);
  assert.match(js, /share_click/);
  assert.match(js, /share_generate_success/);
  assert.match(js, /share_generate_error/);
  assert.match(js, /question_draft_started/);
  assert.match(js, /page_view/);
  assert.match(js, /changed_shell_open/);
  assert.match(js, /changed_followup_click/);
  assert.match(js, /changed_followup/);
  assert.match(js, /followup_question_click/);
  assert.match(js, /backgroundColor: '#f3ece2'/);
  assert.match(html, /fonts\.googleapis\.com\/css2\?family=Cormorant\+Garamond/);
  assert.match(html, /family=Noto\+Sans\+SC/);
  assert.match(html, /family=Noto\+Serif\+SC/);
  assert.match(html, /family=ZCOOL\+XiaoWei/);
});

test('analytics summary translates events into product decisions', () => {
  const analytics = read('scripts/analytics-summary.js');

  assert.match(analytics, /产品判断面板/);
  assert.match(analytics, /北极星指标/);
  assert.match(analytics, /当前最大掉点/);
  assert.match(analytics, /下一步建议/);
  assert.match(analytics, /function rateValue\(/);
  assert.match(analytics, /function findWeakestStep\(/);
  assert.match(analytics, /function buildProductInsights\(/);
  assert.match(analytics, /保存率/);
  assert.match(analytics, /追问率/);
});

test('server exposes privacy-safe analytics endpoint and ignores local analytics logs', () => {
  const server = read('server.js');
  const gitignore = read('.gitignore');

  assert.match(server, /app\.post\('\/api\/track'/);
  assert.match(server, /analytics_events\.log/);
  assert.match(server, /sanitizeAnalyticsPayload/);
  assert.match(server, /不记录用户提问原文/);
  assert.match(server, /sessionId/);
  assert.match(server, /viewportWidth/);
  assert.match(gitignore, /analytics_events\.log/);
});

test('modern followup flow keeps the current result and opens an inline confirmation card', () => {
  const html = read('public/index.html');
  const css = read('public/modern.css');
  const js = read('public/modern.js');

  assert.match(html, /id="modern-followup-composer"[\s\S]*继续看这一层/);
  assert.match(html, /id="modern-followup-question"/);
  assert.match(html, /id="modern-followup-confirm"/);
  assert.match(html, /id="modern-followup-cancel"/);
  assert.match(css, /\.modern-followup-composer/);
  assert.match(css, /\.modern-followup-composer\[hidden\]/);
  assert.match(js, /const followupComposer = document\.getElementById\('modern-followup-composer'\)/);
  assert.match(js, /function showFollowupComposer\(/);
  assert.match(js, /function confirmFollowupQuestion\(/);
  assert.match(js, /followupComposer\.scrollIntoView\(\{ behavior: 'smooth', block: 'center' \}\)/);
  assert.doesNotMatch(functionBlock(js, 'followupFlow'), /resultShell\.hidden = true|composerSection\.scrollIntoView/);
  assert.doesNotMatch(functionBlock(js, 'changedFollowupFlow'), /resultShell\.hidden = true|composerSection\.scrollIntoView/);
});

test('modern question coach recognizes short intent and judgment fallback avoids mechanical divination labels', () => {
  const js = read('public/modern.js');

  assert.match(js, /const SHORT_INTENT_PATTERN = \/\(辞职\|离职\|跳槽/);
  assert.match(js, /const hasShortIntent = SHORT_INTENT_PATTERN\.test\(normalized\)/);
  assert.match(js, /const hasEvent = normalized\.length >= 12 \|\| \(normalized\.length >= 4 && hasShortIntent\)/);
  assert.match(js, /const WEAK_JUDGMENT_PATTERN/);
  assert.match(js, /function getContextualFallbackJudgment\(question\)/);
  assert.match(js, /return pickContextualFallback\(workFallbacks, normalized\)/);
  assert.match(js, /deriveFallbackJudgment\(mainText, emotionText, questionText = ''\)/);
});
